### ISSUE TITLE
BarcodeImage

### ISSUE THREAD

**Issue by hmason55** [team-makeSmart/BarcodeReader#2]
This class will realize all the essential data and methods associated with a 2D pattern, thought of conceptually as an image of a square or rectangular bar code.  Here are the essential ingredients.  This class has very little "smarts" in it, except for the parameterized constructor.  It mostly just stores and retrieves 2D data.

Remember: **BarcodeImage** implements **Cloneable**.

**Comment by Mcghee-Jake** [comment]
- [x] BarcodeImage() {}
- [x] BarcodEImage(String[] str_data)
- [x] public boolean getPixel(int row, int col)
- [x] public boolean getPixel(int row, int col)

**Comment by mdoussias** [comment]
I will try to handle this class. 
Expected completion by Saturday about 4 or 5 pm.

**Comment by mdoussias** [comment]
This class is pretty easy, I have nearly complete.  Expect to have done Friday 03-23-18.
I can help with more after that.

**Comment by mdoussias** [comment]
Having a little trouble understanding this requirement in the spec....  Not sure what it means by 1d string?   Like am I receiveing a value like "My Iphone"... Or is it something more like "*  * *  ***"?

BarcodeImage(String[] str_data) -takes a 1D array of Strings and converts it to the internal 2D array of booleans. 
HINT  -  This constructor is a little tricky because the incoming image is not the necessarily same size as the internal matrix.  So, you have to pack it into the lower-left corner of the double array, causing a bit of stress if you don't like 2D counting.  This is good 2D array exercise.  The DataMatrix class will make sure that there is no extra space below or left of the image so this constructor can put it into the lower-left corner of the array.

**Comment by mdoussias** [comment]
Nevermind I get it now... It's an array.  Not thinking straight.

**Comment by mdoussias** [comment]
Completed class.
I think this should work, but hard to fully test right now without the next, more complicated classes.

If you see anything missing or need anything added, please state here and I can still work on it.

**Comment by p12345vls** [comment]
Need to implement the Clonable interface and create an Object clone() method -- the scan(BarcodeImage bc) in DataMatrix should call this clone method.

**Comment by mdoussias** [comment]
Thank you Pavlos, sorry I missed that on the spec.
I have plans tonight but will get to that early tomorrow morning, as well as fixing the constructors.  Will check back then too to see what else needs done.

**Comment by Mcghee-Jake** [comment]
I'm closing this as I believe this class is complete. Feel free to reopen if I am wrong.
