### ISSUE TITLE
checkSize(String[] data)  needs made in BarcodeImage class

### ISSUE THREAD

**Issue by mdoussias** [team-makeSmart/BarcodeReader#33]
Optional - A private utility method is highly recommended, but not required:  **checkSize(String[] data)**  It does the job of checking the incoming data for every conceivable size or null error.  

**Smaller is okay.**  

**Bigger or null is not.**

Note: Even though this is optional, checking for the correct data is not, so this should be added.

**Comment by mdoussias** [comment]
I am trying to make this now but am confused.....  
This would go in the BarcodeImage(Str[]) constructor to check the string value isn't too long and isn't null...

**If the data is bad, should I:**
1.)  Throw an exception?
2.) Should I alter the string and return the altered string so that the bottom left of the string is used to finish initializing the object?
3.) Should I just create a blank object?

Not sure what the professor wants.

**Comment by mdoussias** [comment]
This is still open pending a question to the instructor for clarification, but can be added quickly once we have direction.

**Comment by Mcghee-Jake** [comment]
If we get a response from the professor that would be good, but my initial intuition is that we can handle bad data however we want as long as its handled gracefully enough. Id say that we should just print something to the console warning that the data is bad and then fill the barcodeimage with a blanks. Id argue that is a better solution than throwing an exception, since throwing an exception stops the rest of the program from running. Option 2 would work, but TBQH I don't that is worth the effort since that would take the most time to write, and could still definitely feed in bad data unintentionally.

**Comment by mdoussias** [comment]
I got a response from the professor and I will fix now.

Just going to have the checkSize(String[] data)return false in the constructor and then have it skip the initialization and create an empty image.

**Comment by mdoussias** [comment]
This should not affect any of the rest of the program.

**Comment by mdoussias** [comment]
This was completed and tested.
