### ISSUE TITLE
Discussion Extra docs

### ISSUE THREAD

**Issue by mdoussias** [team-makeSmart/BarcodeReader#5]
I'm not sure what all the extra docs are for here?  

Is this som sort of connection files for when you use github on your desktop?

**Comment by hmason55** [comment]
Some of them like .gitattributes and .gitignore are for the repo settings, we shouldn't need to change any of those but I may add some stuff later to the .gitignore file.

The readme isn't really necessary but is there in case we want to add anything to it.
The license is just a standard license for our code since the repo is public.
Everything else is for the eclipse project you should be able to just import it.
The actual files we will be editing are in the /src directory.
I will probably add the eclipse project files outside of /src to the .gitignore later so that we don't have to update those everytime someone changes something on their local project settings.

**Comment by hmason55** [comment]
To simplify things I like to use github for desktop, it has a really simple ui and you can push, pull, commit, merge etc with a couple clicks.

Here is a link if you are interested:
[desktop.github.com](desktop.github.com)

**Comment by mdoussias** [comment]
Cool.  I may be slow to integrate this this week, but I will start on it and try to be up to speed for a week or two from now.

I'm leaving this issue open only so others may read.  Thank you for the links Hunter.
